export default function Home() {
  return (
    <main className="min-h-screen bg-white">

      {/* HERO SECTION */}
      <section className="flex flex-col items-center text-center px-6 py-20">
        <h1 className="text-4xl md:text-6xl font-bold mb-4">
          Boost Your Productivity with AutoBotWa
        </h1>

        <p className="text-gray-600 text-lg md:text-xl max-w-2xl mb-6">
          Build fast, modern, and responsive web applications using AI-powered UI components.
        </p>

        <button className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg text-lg">
          Get Started
        </button>
      </section>

      {/* FEATURES SECTION */}
      <section className="bg-gray-50 py-16 px-6">
        <h2 className="text-3xl font-bold text-center mb-10">
          Powerful Features
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
          
          {/* Feature 1 */}
          <div className="p-6 shadow-md rounded-xl bg-white">
            <h3 className="text-xl font-semibold mb-3">Fast Performance</h3>
            <p className="text-gray-600">
              Experience blazing fast load times and optimized performance.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="p-6 shadow-md rounded-xl bg-white">
            <h3 className="text-xl font-semibold mb-3">AI Powered</h3>
            <p className="text-gray-600">
              Use AI to generate beautiful UI sections instantly.
            </p>
          </div>

          {/* Feature 3 */}
          <div className="p-6 shadow-md rounded-xl bg-white">
            <h3 className="text-xl font-semibold mb-3">Responsive Design</h3>
            <p className="text-gray-600">
              Fully optimized for mobile, tablet, and desktop screens.
            </p>
          </div>

        </div>
      </section>
      
    {/* TESTIMONIALS SECTION */}
<section className="py-16 px-6">
  <h2 className="text-3xl font-bold text-center mb-10">
    What Users Say
  </h2>

  <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">

    {/* Testimonial 1 */}
    <div className="p-6 shadow-md rounded-xl bg-white">
      <p className="text-gray-700 mb-4">
        “The UI components generated by the AI saved me hours of work!”
      </p>
      <h4 className="font-semibold">— Riya Sharma</h4>
    </div>

    {/* Testimonial 2 */}
    <div className="p-6 shadow-md rounded-xl bg-white">
      <p className="text-gray-700 mb-4">
        “Clean design, fast performance, and easy to integrate.”
      </p>
      <h4 className="font-semibold">— Arjun Patel</h4>
    </div>

    {/* Testimonial 3 */}
    <div className="p-6 shadow-md rounded-xl bg-white">
      <p className="text-gray-700 mb-4">
        “Loved the responsive layout! Works perfectly on my phone.”
      </p>
      <h4 className="font-semibold">— Sneha Mehta</h4>
    </div>

  </div>
</section>
  
  {/* PRICING SECTION */}
<section className="bg-gray-50 py-16 px-6">
  <h2 className="text-3xl font-bold text-center mb-10">
    Simple Pricing
  </h2>

  <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">

    {/* Basic Plan */}
    <div className="p-6 shadow-md rounded-xl bg-white text-center">
      <h3 className="text-xl font-bold mb-3">Basic</h3>
      <p className="text-4xl font-bold mb-3">₹0</p>
      <p className="text-gray-600 mb-6">Perfect for beginners</p>
      <button className="bg-blue-600 text-white px-5 py-2 rounded-lg">
        Get Started
      </button>
    </div>

    {/* Pro Plan */}
    <div className="p-6 shadow-md rounded-xl bg-white text-center border-2 border-blue-600">
      <h3 className="text-xl font-bold mb-3">Pro</h3>
      <p className="text-4xl font-bold mb-3">₹499</p>
      <p className="text-gray-600 mb-6">For serious developers</p>
      <button className="bg-blue-600 text-white px-5 py-2 rounded-lg">
        Choose Plan
      </button>
    </div>

    {/* Premium Plan */}
    <div className="p-6 shadow-md rounded-xl bg-white text-center">
      <h3 className="text-xl font-bold mb-3">Premium</h3>
      <p className="text-4xl font-bold mb-3">₹999</p>
      <p className="text-gray-600 mb-6">For advanced teams</p>
      <button className="bg-blue-600 text-white px-5 py-2 rounded-lg">
        Buy Now
      </button>
    </div>

  </div>
</section>

{/* FOOTER SECTION */}
<footer className="bg-black text-white py-6 px-6 mt-10">
  <div className="max-w-4xl mx-auto text-center">
    <h3 className="text-lg font-semibold mb-2">AutoBotWa</h3>
    <p className="text-gray-400 text-sm mb-4">
      Modern, Fast & AI Powered Web Solutions.
    </p>

    <p className="text-gray-500 text-xs">
      © {new Date().getFullYear()} AutoBotWa. All rights reserved.
    </p>
  </div>
</footer>


    </main>
  );
}
